// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyRecord = `-- name: CompleteIdempotencyRecord :one
UPDATE platform.idempotency_records
SET response_status = $1,
    response_body = $2,
    response_protected = $3,
    completed_at = $4
WHERE id = $5 AND response_status IS NULL
RETURNING id, scope, tenant_id, actor_id, method, canonical_route, idempotency_key, request_hash, response_status, response_body, response_protected, created_at, completed_at, expires_at
`

type CompleteIdempotencyRecordParams struct {
	ResponseStatus    pgtype.Int4
	ResponseBody      []byte
	ResponseProtected bool
	CompletedAt       *time.Time
	ID                uuid.UUID
}

func (q *Queries) CompleteIdempotencyRecord(ctx context.Context, arg CompleteIdempotencyRecordParams) (PlatformIdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyRecord,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ResponseProtected,
		arg.CompletedAt,
		arg.ID,
	)
	var i PlatformIdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ActorID,
		&i.Method,
		&i.CanonicalRoute,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResponseProtected,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyRecords = `-- name: DeleteExpiredIdempotencyRecords :execrows
DELETE FROM platform.idempotency_records WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredIdempotencyRecords(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyRecords, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyRecordForUpdate = `-- name: GetIdempotencyRecordForUpdate :one
SELECT id, scope, tenant_id, actor_id, method, canonical_route, idempotency_key, request_hash, response_status, response_body, response_protected, created_at, completed_at, expires_at FROM platform.idempotency_records
WHERE scope = $1
  AND tenant_id IS NOT DISTINCT FROM $2::uuid
  AND actor_id = $3
  AND method = $4
  AND canonical_route = $5
  AND idempotency_key = $6
FOR UPDATE
`

type GetIdempotencyRecordForUpdateParams struct {
	Scope          string
	TenantID       *uuid.UUID
	ActorID        uuid.UUID
	Method         string
	CanonicalRoute string
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyRecordForUpdate(ctx context.Context, arg GetIdempotencyRecordForUpdateParams) (PlatformIdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecordForUpdate,
		arg.Scope,
		arg.TenantID,
		arg.ActorID,
		arg.Method,
		arg.CanonicalRoute,
		arg.IdempotencyKey,
	)
	var i PlatformIdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ActorID,
		&i.Method,
		&i.CanonicalRoute,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResponseProtected,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const reserveIdempotencyRecord = `-- name: ReserveIdempotencyRecord :one
INSERT INTO platform.idempotency_records (
    id, scope, tenant_id, actor_id, method, canonical_route, idempotency_key,
    request_hash, response_status, response_body, response_protected, created_at, completed_at, expires_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, NULL, NULL, false, $9, NULL, $10
)
ON CONFLICT (scope, tenant_id, actor_id, method, canonical_route, idempotency_key)
DO NOTHING
RETURNING id, scope, tenant_id, actor_id, method, canonical_route, idempotency_key, request_hash, response_status, response_body, response_protected, created_at, completed_at, expires_at
`

type ReserveIdempotencyRecordParams struct {
	ID             uuid.UUID
	Scope          string
	TenantID       *uuid.UUID
	ActorID        uuid.UUID
	Method         string
	CanonicalRoute string
	IdempotencyKey string
	RequestHash    []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

func (q *Queries) ReserveIdempotencyRecord(ctx context.Context, arg ReserveIdempotencyRecordParams) (PlatformIdempotencyRecord, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyRecord,
		arg.ID,
		arg.Scope,
		arg.TenantID,
		arg.ActorID,
		arg.Method,
		arg.CanonicalRoute,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i PlatformIdempotencyRecord
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ActorID,
		&i.Method,
		&i.CanonicalRoute,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ResponseProtected,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}
