// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformIdempotencyRecord struct {
	ID                uuid.UUID
	Scope             string
	TenantID          *uuid.UUID
	ActorID           uuid.UUID
	Method            string
	CanonicalRoute    string
	IdempotencyKey    string
	RequestHash       []byte
	ResponseStatus    pgtype.Int4
	ResponseBody      []byte
	ResponseProtected bool
	CreatedAt         time.Time
	CompletedAt       *time.Time
	ExpiresAt         time.Time
}

type TenancyMembership struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	IdentityID uuid.UUID
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TenancyRoleBinding struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	MembershipID uuid.UUID
	Role         string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TenancyTenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	State     string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
