// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const completeOutboxEvent = `-- name: CompleteOutboxEvent :execrows
UPDATE platform.outbox_events
SET processed_at = $1,
    lease_owner = NULL,
    lease_deadline = NULL
WHERE id = $2
  AND lease_owner = $3
  AND processed_at IS NULL
`

type CompleteOutboxEventParams struct {
	ProcessedAt *time.Time
	ID          uuid.UUID
	OwnerID     *uuid.UUID
}

func (q *Queries) CompleteOutboxEvent(ctx context.Context, arg CompleteOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOutboxEvent, arg.ProcessedAt, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuditAndOutbox = `-- name: InsertAuditAndOutbox :exec
WITH inserted_audit AS (
INSERT INTO audit.audit_events (
    id,
    tenant_id,
    actor_type,
    actor_id,
    action,
    resource_type,
    resource_id,
    result,
    source_ip,
    user_agent,
    request_id,
    details,
    created_at
) VALUES (
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22
)
RETURNING id
)
INSERT INTO platform.outbox_events (
    id,
    tenant_id,
    event_type,
    aggregate_type,
    aggregate_id,
    payload_version,
    payload,
    created_at,
    available_at
)
SELECT $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       $7,
       $8,
       $9
FROM inserted_audit
`

type InsertAuditAndOutboxParams struct {
	OutboxID        uuid.UUID
	OutboxTenantID  *uuid.UUID
	EventType       string
	AggregateType   string
	AggregateID     uuid.UUID
	PayloadVersion  int32
	Payload         []byte
	OutboxCreatedAt time.Time
	AvailableAt     time.Time
	AuditID         uuid.UUID
	AuditTenantID   *uuid.UUID
	ActorType       string
	ActorID         *uuid.UUID
	Action          string
	ResourceType    string
	ResourceID      *uuid.UUID
	Result          string
	SourceIp        netip.Addr
	UserAgent       string
	RequestID       uuid.UUID
	Details         []byte
	AuditCreatedAt  time.Time
}

func (q *Queries) InsertAuditAndOutbox(ctx context.Context, arg InsertAuditAndOutboxParams) error {
	_, err := q.db.Exec(ctx, insertAuditAndOutbox,
		arg.OutboxID,
		arg.OutboxTenantID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.PayloadVersion,
		arg.Payload,
		arg.OutboxCreatedAt,
		arg.AvailableAt,
		arg.AuditID,
		arg.AuditTenantID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Result,
		arg.SourceIp,
		arg.UserAgent,
		arg.RequestID,
		arg.Details,
		arg.AuditCreatedAt,
	)
	return err
}

const leaseOutboxEvents = `-- name: LeaseOutboxEvents :many
WITH candidates AS (
    SELECT id
    FROM platform.outbox_events
    WHERE processed_at IS NULL
      AND available_at <= $1::timestamptz
      AND (lease_deadline IS NULL OR lease_deadline <= $1::timestamptz)
    ORDER BY available_at, created_at, id
    FOR UPDATE SKIP LOCKED
    LIMIT $2::integer
), leased AS (
    UPDATE platform.outbox_events AS event
    SET lease_owner = $3,
        lease_deadline = $4,
        attempts = event.attempts + 1
    FROM candidates
    WHERE event.id = candidates.id
    RETURNING event.id,
              event.tenant_id,
              event.event_type,
              event.aggregate_type,
              event.aggregate_id,
              event.payload_version,
              event.payload,
              event.created_at,
              event.available_at,
              event.lease_owner,
              event.lease_deadline,
              event.attempts,
              event.processed_at
)
SELECT id,
       tenant_id,
       event_type,
       aggregate_type,
       aggregate_id,
       payload_version,
       payload,
       created_at,
       available_at,
       lease_owner,
       lease_deadline,
       attempts,
       processed_at
FROM leased
ORDER BY available_at, created_at, id
`

type LeaseOutboxEventsParams struct {
	LeaseNow      time.Time
	BatchLimit    int32
	OwnerID       *uuid.UUID
	LeaseDeadline *time.Time
}

type LeaseOutboxEventsRow struct {
	ID             uuid.UUID
	TenantID       *uuid.UUID
	EventType      string
	AggregateType  string
	AggregateID    uuid.UUID
	PayloadVersion int32
	Payload        []byte
	CreatedAt      time.Time
	AvailableAt    time.Time
	LeaseOwner     *uuid.UUID
	LeaseDeadline  *time.Time
	Attempts       int32
	ProcessedAt    *time.Time
}

func (q *Queries) LeaseOutboxEvents(ctx context.Context, arg LeaseOutboxEventsParams) ([]LeaseOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, leaseOutboxEvents,
		arg.LeaseNow,
		arg.BatchLimit,
		arg.OwnerID,
		arg.LeaseDeadline,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaseOutboxEventsRow
	for rows.Next() {
		var i LeaseOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.PayloadVersion,
			&i.Payload,
			&i.CreatedAt,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseDeadline,
			&i.Attempts,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, tenant_id, actor_type, actor_id, action, resource_type, resource_id,
       result, source_ip, user_agent, request_id, created_at
FROM audit.audit_events
WHERE ($1::uuid IS NULL OR tenant_id = $1)
  AND (created_at, id) > ($2::timestamptz, $3::uuid)
ORDER BY created_at, id
LIMIT $4
`

type ListAuditEventsParams struct {
	TenantID       *uuid.UUID
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

type ListAuditEventsRow struct {
	ID           uuid.UUID
	TenantID     *uuid.UUID
	ActorType    string
	ActorID      *uuid.UUID
	Action       string
	ResourceType string
	ResourceID   *uuid.UUID
	Result       string
	SourceIp     netip.Addr
	UserAgent    string
	RequestID    uuid.UUID
	CreatedAt    time.Time
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.TenantID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Result,
			&i.SourceIp,
			&i.UserAgent,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseOutboxEvent = `-- name: ReleaseOutboxEvent :execrows
UPDATE platform.outbox_events
SET available_at = $1,
    lease_owner = NULL,
    lease_deadline = NULL
WHERE id = $2
  AND lease_owner = $3
  AND processed_at IS NULL
`

type ReleaseOutboxEventParams struct {
	AvailableAt time.Time
	ID          uuid.UUID
	OwnerID     *uuid.UUID
}

func (q *Queries) ReleaseOutboxEvent(ctx context.Context, arg ReleaseOutboxEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseOutboxEvent, arg.AvailableAt, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
