// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuditAuditEvent struct {
	ID           uuid.UUID
	TenantID     *uuid.UUID
	ActorType    string
	ActorID      *uuid.UUID
	Action       string
	ResourceType string
	ResourceID   *uuid.UUID
	Result       string
	SourceIp     netip.Addr
	UserAgent    string
	RequestID    uuid.UUID
	Details      []byte
	CreatedAt    time.Time
}

type PlatformOutboxEvent struct {
	ID             uuid.UUID
	TenantID       *uuid.UUID
	EventType      string
	AggregateType  string
	AggregateID    uuid.UUID
	PayloadVersion int32
	Payload        []byte
	CreatedAt      time.Time
	AvailableAt    time.Time
	LeaseOwner     *uuid.UUID
	LeaseDeadline  *time.Time
	Attempts       int32
	ProcessedAt    *time.Time
}
