// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getOperation = `-- name: GetOperation :one
SELECT id, tenant_id, operation_type, resource_type, resource_id, requested_generation, state, attempts, progress_category, result_code, safe_message, requested_by, started_at, completed_at, created_at, updated_at FROM operations.operations WHERE id=$1 AND (tenant_id=$2 OR ($2::uuid IS NULL AND tenant_id IS NULL))
`

type GetOperationParams struct {
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (OperationsOperation, error) {
	row := q.db.QueryRow(ctx, getOperation, arg.ID, arg.TenantID)
	var i OperationsOperation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OperationType,
		&i.ResourceType,
		&i.ResourceID,
		&i.RequestedGeneration,
		&i.State,
		&i.Attempts,
		&i.ProgressCategory,
		&i.ResultCode,
		&i.SafeMessage,
		&i.RequestedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantOperations = `-- name: ListTenantOperations :many
SELECT id, tenant_id, operation_type, resource_type, resource_id, requested_generation, state, attempts, progress_category, result_code, safe_message, requested_by, started_at, completed_at, created_at, updated_at FROM operations.operations WHERE tenant_id=$1 AND (created_at,id)<($2,$3)
ORDER BY created_at DESC,id DESC LIMIT $4
`

type ListTenantOperationsParams struct {
	TenantID    *uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
}

func (q *Queries) ListTenantOperations(ctx context.Context, arg ListTenantOperationsParams) ([]OperationsOperation, error) {
	rows, err := q.db.Query(ctx, listTenantOperations,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationsOperation
	for rows.Next() {
		var i OperationsOperation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OperationType,
			&i.ResourceType,
			&i.ResourceID,
			&i.RequestedGeneration,
			&i.State,
			&i.Attempts,
			&i.ProgressCategory,
			&i.ResultCode,
			&i.SafeMessage,
			&i.RequestedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
