// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_profiles.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getAccessProfile = `-- name: GetAccessProfile :one
SELECT tenant_id, endpoint_id, protocols, dns_mode, source_cidrs, target_allow_cidrs, target_deny_cidrs, target_allow_domains, target_deny_domains, allowed_ports, policy_document, policy_hash, max_connections, max_connection_rate, idle_timeout_seconds, max_bytes_per_connection, traffic_window_seconds, max_window_bytes, version, created_at, updated_at FROM endpoints.access_profiles WHERE tenant_id=$1 AND endpoint_id=$2
`

type GetAccessProfileParams struct {
	TenantID   uuid.UUID
	EndpointID uuid.UUID
}

func (q *Queries) GetAccessProfile(ctx context.Context, arg GetAccessProfileParams) (EndpointsAccessProfile, error) {
	row := q.db.QueryRow(ctx, getAccessProfile, arg.TenantID, arg.EndpointID)
	var i EndpointsAccessProfile
	err := row.Scan(
		&i.TenantID,
		&i.EndpointID,
		&i.Protocols,
		&i.DnsMode,
		&i.SourceCidrs,
		&i.TargetAllowCidrs,
		&i.TargetDenyCidrs,
		&i.TargetAllowDomains,
		&i.TargetDenyDomains,
		&i.AllowedPorts,
		&i.PolicyDocument,
		&i.PolicyHash,
		&i.MaxConnections,
		&i.MaxConnectionRate,
		&i.IdleTimeoutSeconds,
		&i.MaxBytesPerConnection,
		&i.TrafficWindowSeconds,
		&i.MaxWindowBytes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
