// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const currentContext = `-- name: CurrentContext :one
SELECT platform.current_tenant_id() AS tenant_id,
       platform.current_actor_id() AS actor_id
`

type CurrentContextRow struct {
	TenantID uuid.UUID
	ActorID  uuid.UUID
}

func (q *Queries) CurrentContext(ctx context.Context) (CurrentContextRow, error) {
	row := q.db.QueryRow(ctx, currentContext)
	var i CurrentContextRow
	err := row.Scan(&i.TenantID, &i.ActorID)
	return i, err
}
