// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: local_identity.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumeLocalRecoveryCode = `-- name: ConsumeLocalRecoveryCode :one
UPDATE identity.local_recovery_codes
SET used_at = $1
WHERE id = $2 AND identity_id = $3 AND used_at IS NULL
RETURNING id, identity_id, verifier, used_at, created_at
`

type ConsumeLocalRecoveryCodeParams struct {
	UsedAt     *time.Time
	ID         uuid.UUID
	IdentityID uuid.UUID
}

func (q *Queries) ConsumeLocalRecoveryCode(ctx context.Context, arg ConsumeLocalRecoveryCodeParams) (IdentityLocalRecoveryCode, error) {
	row := q.db.QueryRow(ctx, consumeLocalRecoveryCode, arg.UsedAt, arg.ID, arg.IdentityID)
	var i IdentityLocalRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Verifier,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countLocalAdmins = `-- name: CountLocalAdmins :one
SELECT count(*) FROM identity.local_admins
`

func (q *Queries) CountLocalAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLocalAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedLocalLoginsBySource = `-- name: CountRecentFailedLocalLoginsBySource :one
SELECT count(*)
FROM identity.local_login_attempts
WHERE source_ip = $1
  AND success = false
  AND attempted_at >= $2
`

type CountRecentFailedLocalLoginsBySourceParams struct {
	SourceIp       netip.Addr
	AttemptedSince time.Time
}

func (q *Queries) CountRecentFailedLocalLoginsBySource(ctx context.Context, arg CountRecentFailedLocalLoginsBySourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedLocalLoginsBySource, arg.SourceIp, arg.AttemptedSince)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLocalAdmin = `-- name: CreateLocalAdmin :one
INSERT INTO identity.local_admins (
    identity_id, identifier, display_name, password_verifier, totp_ciphertext,
    failed_attempts, locked_until, last_authenticated_at, version, created_at, updated_at
)
VALUES (
    $1, $2, $3,
    $4, $5, 0, NULL, NULL, 1,
    $6, $7
)
RETURNING identity_id, identifier, display_name, password_verifier, totp_ciphertext,
          failed_attempts, locked_until, last_authenticated_at, version, created_at, updated_at
`

type CreateLocalAdminParams struct {
	IdentityID       uuid.UUID
	Identifier       string
	DisplayName      string
	PasswordVerifier string
	TotpCiphertext   []byte
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type CreateLocalAdminRow struct {
	IdentityID          uuid.UUID
	Identifier          string
	DisplayName         string
	PasswordVerifier    string
	TotpCiphertext      []byte
	FailedAttempts      int32
	LockedUntil         *time.Time
	LastAuthenticatedAt *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) CreateLocalAdmin(ctx context.Context, arg CreateLocalAdminParams) (CreateLocalAdminRow, error) {
	row := q.db.QueryRow(ctx, createLocalAdmin,
		arg.IdentityID,
		arg.Identifier,
		arg.DisplayName,
		arg.PasswordVerifier,
		arg.TotpCiphertext,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateLocalAdminRow
	err := row.Scan(
		&i.IdentityID,
		&i.Identifier,
		&i.DisplayName,
		&i.PasswordVerifier,
		&i.TotpCiphertext,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastAuthenticatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocalRecoveryCode = `-- name: CreateLocalRecoveryCode :one
INSERT INTO identity.local_recovery_codes (id, identity_id, verifier, used_at, created_at)
VALUES ($1, $2, $3, NULL, $4)
RETURNING id, identity_id, verifier, used_at, created_at
`

type CreateLocalRecoveryCodeParams struct {
	ID         uuid.UUID
	IdentityID uuid.UUID
	Verifier   string
	CreatedAt  time.Time
}

func (q *Queries) CreateLocalRecoveryCode(ctx context.Context, arg CreateLocalRecoveryCodeParams) (IdentityLocalRecoveryCode, error) {
	row := q.db.QueryRow(ctx, createLocalRecoveryCode,
		arg.ID,
		arg.IdentityID,
		arg.Verifier,
		arg.CreatedAt,
	)
	var i IdentityLocalRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Verifier,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO identity.user_identities (id, tenant_eligible, disabled_at, version, created_at, updated_at)
VALUES ($1, false, NULL, 1, $2, $3)
RETURNING id, tenant_eligible, disabled_at, version, created_at, updated_at
`

type CreateUserIdentityParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (IdentityUserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity, arg.ID, arg.CreatedAt, arg.UpdatedAt)
	var i IdentityUserIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantEligible,
		&i.DisabledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAdminByIdentifier = `-- name: GetLocalAdminByIdentifier :one
SELECT admin.identity_id, admin.identifier, admin.display_name, admin.password_verifier,
       admin.totp_ciphertext, admin.failed_attempts, admin.locked_until,
       admin.last_authenticated_at, admin.version, admin.created_at, admin.updated_at,
       principal.disabled_at
FROM identity.local_admins AS admin
JOIN identity.user_identities AS principal ON principal.id = admin.identity_id
WHERE admin.identifier = $1
`

type GetLocalAdminByIdentifierRow struct {
	IdentityID          uuid.UUID
	Identifier          string
	DisplayName         string
	PasswordVerifier    string
	TotpCiphertext      []byte
	FailedAttempts      int32
	LockedUntil         *time.Time
	LastAuthenticatedAt *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DisabledAt          *time.Time
}

func (q *Queries) GetLocalAdminByIdentifier(ctx context.Context, identifier string) (GetLocalAdminByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getLocalAdminByIdentifier, identifier)
	var i GetLocalAdminByIdentifierRow
	err := row.Scan(
		&i.IdentityID,
		&i.Identifier,
		&i.DisplayName,
		&i.PasswordVerifier,
		&i.TotpCiphertext,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastAuthenticatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getLocalAdminByIdentifierForUpdate = `-- name: GetLocalAdminByIdentifierForUpdate :one
SELECT admin.identity_id, admin.identifier, admin.display_name, admin.password_verifier,
       admin.totp_ciphertext, admin.failed_attempts, admin.locked_until,
       admin.last_authenticated_at, admin.version, admin.created_at, admin.updated_at,
       principal.disabled_at
FROM identity.local_admins AS admin
JOIN identity.user_identities AS principal ON principal.id = admin.identity_id
WHERE admin.identifier = $1
FOR UPDATE OF admin
`

type GetLocalAdminByIdentifierForUpdateRow struct {
	IdentityID          uuid.UUID
	Identifier          string
	DisplayName         string
	PasswordVerifier    string
	TotpCiphertext      []byte
	FailedAttempts      int32
	LockedUntil         *time.Time
	LastAuthenticatedAt *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DisabledAt          *time.Time
}

func (q *Queries) GetLocalAdminByIdentifierForUpdate(ctx context.Context, identifier string) (GetLocalAdminByIdentifierForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLocalAdminByIdentifierForUpdate, identifier)
	var i GetLocalAdminByIdentifierForUpdateRow
	err := row.Scan(
		&i.IdentityID,
		&i.Identifier,
		&i.DisplayName,
		&i.PasswordVerifier,
		&i.TotpCiphertext,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastAuthenticatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listUnusedLocalRecoveryCodes = `-- name: ListUnusedLocalRecoveryCodes :many
SELECT id, identity_id, verifier, used_at, created_at
FROM identity.local_recovery_codes
WHERE identity_id = $1 AND used_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListUnusedLocalRecoveryCodes(ctx context.Context, identityID uuid.UUID) ([]IdentityLocalRecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedLocalRecoveryCodes, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityLocalRecoveryCode
	for rows.Next() {
		var i IdentityLocalRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Verifier,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLocalAdminBootstrap = `-- name: LockLocalAdminBootstrap :exec
SELECT pg_advisory_xact_lock(hashtextextended('ajiasu-local-admin-bootstrap', 0))
`

func (q *Queries) LockLocalAdminBootstrap(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockLocalAdminBootstrap)
	return err
}

const lockLocalLoginSource = `-- name: LockLocalLoginSource :exec
SELECT pg_advisory_xact_lock(hashtextextended('ajiasu-local-login-source:' || $1::inet::text, 0))
`

func (q *Queries) LockLocalLoginSource(ctx context.Context, sourceIp netip.Addr) error {
	_, err := q.db.Exec(ctx, lockLocalLoginSource, sourceIp)
	return err
}

const recordLocalAdminFailure = `-- name: RecordLocalAdminFailure :one
UPDATE identity.local_admins
SET failed_attempts = failed_attempts + 1,
    locked_until = COALESCE($1, locked_until),
    version = version + 1,
    updated_at = $2
WHERE identity_id = $3
RETURNING identity_id, identifier, display_name, password_verifier, totp_ciphertext,
          failed_attempts, locked_until, last_authenticated_at, version, created_at, updated_at
`

type RecordLocalAdminFailureParams struct {
	LockedUntil *time.Time
	UpdatedAt   time.Time
	IdentityID  uuid.UUID
}

type RecordLocalAdminFailureRow struct {
	IdentityID          uuid.UUID
	Identifier          string
	DisplayName         string
	PasswordVerifier    string
	TotpCiphertext      []byte
	FailedAttempts      int32
	LockedUntil         *time.Time
	LastAuthenticatedAt *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) RecordLocalAdminFailure(ctx context.Context, arg RecordLocalAdminFailureParams) (RecordLocalAdminFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLocalAdminFailure, arg.LockedUntil, arg.UpdatedAt, arg.IdentityID)
	var i RecordLocalAdminFailureRow
	err := row.Scan(
		&i.IdentityID,
		&i.Identifier,
		&i.DisplayName,
		&i.PasswordVerifier,
		&i.TotpCiphertext,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastAuthenticatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordLocalLoginAttempt = `-- name: RecordLocalLoginAttempt :exec
INSERT INTO identity.local_login_attempts (
    id, identity_id, identifier_digest, source_ip, success, reason, attempted_at
)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type RecordLocalLoginAttemptParams struct {
	ID               uuid.UUID
	IdentityID       *uuid.UUID
	IdentifierDigest []byte
	SourceIp         netip.Addr
	Success          bool
	Reason           string
	AttemptedAt      time.Time
}

func (q *Queries) RecordLocalLoginAttempt(ctx context.Context, arg RecordLocalLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, recordLocalLoginAttempt,
		arg.ID,
		arg.IdentityID,
		arg.IdentifierDigest,
		arg.SourceIp,
		arg.Success,
		arg.Reason,
		arg.AttemptedAt,
	)
	return err
}

const resetLocalAdminFailures = `-- name: ResetLocalAdminFailures :one
UPDATE identity.local_admins
SET failed_attempts = 0,
    locked_until = NULL,
    last_authenticated_at = $1,
    version = version + 1,
    updated_at = $1
WHERE identity_id = $2
RETURNING identity_id, identifier, display_name, password_verifier, totp_ciphertext,
          failed_attempts, locked_until, last_authenticated_at, version, created_at, updated_at
`

type ResetLocalAdminFailuresParams struct {
	AuthenticatedAt *time.Time
	IdentityID      uuid.UUID
}

type ResetLocalAdminFailuresRow struct {
	IdentityID          uuid.UUID
	Identifier          string
	DisplayName         string
	PasswordVerifier    string
	TotpCiphertext      []byte
	FailedAttempts      int32
	LockedUntil         *time.Time
	LastAuthenticatedAt *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ResetLocalAdminFailures(ctx context.Context, arg ResetLocalAdminFailuresParams) (ResetLocalAdminFailuresRow, error) {
	row := q.db.QueryRow(ctx, resetLocalAdminFailures, arg.AuthenticatedAt, arg.IdentityID)
	var i ResetLocalAdminFailuresRow
	err := row.Scan(
		&i.IdentityID,
		&i.Identifier,
		&i.DisplayName,
		&i.PasswordVerifier,
		&i.TotpCiphertext,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastAuthenticatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
