// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type IdentityAuthSession struct {
	ID                uuid.UUID
	IdentityID        uuid.UUID
	TokenDigest       []byte
	CsrfDigest        []byte
	IssuedAt          time.Time
	LastUsedAt        time.Time
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         *time.Time
	Version           int64
}

type IdentityLocalAdmin struct {
	IdentityID          uuid.UUID
	TenantEligible      bool
	Singleton           bool
	Identifier          string
	DisplayName         string
	PasswordVerifier    string
	TotpCiphertext      []byte
	FailedAttempts      int32
	LockedUntil         *time.Time
	LastAuthenticatedAt *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type IdentityLocalLoginAttempt struct {
	ID               uuid.UUID
	IdentityID       *uuid.UUID
	IdentifierDigest []byte
	SourceIp         netip.Addr
	Success          bool
	Reason           string
	AttemptedAt      time.Time
}

type IdentityLocalRecoveryCode struct {
	ID         uuid.UUID
	IdentityID uuid.UUID
	Verifier   string
	UsedAt     *time.Time
	CreatedAt  time.Time
}

type IdentityOidcAuthTransaction struct {
	ID                     uuid.UUID
	StateDigest            []byte
	BindingDigest          []byte
	NonceDigest            []byte
	PkceVerifierCiphertext []byte
	ReturnPath             string
	ExpiresAt              time.Time
	ConsumedAt             *time.Time
	CreatedAt              time.Time
}

type IdentityOidcIdentity struct {
	ID          uuid.UUID
	IdentityID  uuid.UUID
	Issuer      string
	Subject     string
	Email       string
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type IdentityServiceIdentity struct {
	ID         uuid.UUID
	Scope      string
	TenantID   *uuid.UUID
	ScopeKey   *uuid.UUID
	Name       string
	DisabledAt *time.Time
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type IdentityServiceToken struct {
	ID                uuid.UUID
	ServiceIdentityID uuid.UUID
	Scope             string
	TenantID          *uuid.UUID
	ScopeKey          *uuid.UUID
	Prefix            string
	Verifier          string
	Role              string
	SourceCidr        *netip.Prefix
	ExpiresAt         time.Time
	RevokedAt         *time.Time
	CreatedAt         time.Time
}

type IdentityUserIdentity struct {
	ID             uuid.UUID
	TenantEligible bool
	DisabledAt     *time.Time
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type TenancyMembership struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	IdentityID             uuid.UUID
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	IdentityTenantEligible bool
}

type TenancyRoleBinding struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	MembershipID uuid.UUID
	Role         string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TenancyTenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	State     string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
