// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOIDCAuthTransaction = `-- name: ConsumeOIDCAuthTransaction :one
UPDATE identity.oidc_auth_transactions
SET consumed_at = $1
WHERE state_digest = $2
  AND binding_digest = $3
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, state_digest, binding_digest, nonce_digest, pkce_verifier_ciphertext, return_path, expires_at, consumed_at, created_at
`

type ConsumeOIDCAuthTransactionParams struct {
	ConsumedAt    *time.Time
	StateDigest   []byte
	BindingDigest []byte
}

func (q *Queries) ConsumeOIDCAuthTransaction(ctx context.Context, arg ConsumeOIDCAuthTransactionParams) (IdentityOidcAuthTransaction, error) {
	row := q.db.QueryRow(ctx, consumeOIDCAuthTransaction, arg.ConsumedAt, arg.StateDigest, arg.BindingDigest)
	var i IdentityOidcAuthTransaction
	err := row.Scan(
		&i.ID,
		&i.StateDigest,
		&i.BindingDigest,
		&i.NonceDigest,
		&i.PkceVerifierCiphertext,
		&i.ReturnPath,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO identity.auth_sessions (
    id, identity_id, token_digest, csrf_digest, issued_at, last_used_at,
    idle_expires_at, absolute_expires_at, revoked_at, version
) VALUES (
    $1, $2, $3, $4,
    $5, $5, $6,
    $7, NULL, 1
)
RETURNING id, identity_id, token_digest, csrf_digest, issued_at, last_used_at, idle_expires_at, absolute_expires_at, revoked_at, version
`

type CreateAuthSessionParams struct {
	ID                uuid.UUID
	IdentityID        uuid.UUID
	TokenDigest       []byte
	CsrfDigest        []byte
	IssuedAt          time.Time
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (IdentityAuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.IdentityID,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.IssuedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i IdentityAuthSession
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.Version,
	)
	return i, err
}

const createOIDCAuthTransaction = `-- name: CreateOIDCAuthTransaction :one
INSERT INTO identity.oidc_auth_transactions (
    id, state_digest, binding_digest, nonce_digest, pkce_verifier_ciphertext, return_path, expires_at, consumed_at, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, NULL, $8
)
RETURNING id, state_digest, binding_digest, nonce_digest, pkce_verifier_ciphertext, return_path, expires_at, consumed_at, created_at
`

type CreateOIDCAuthTransactionParams struct {
	ID                     uuid.UUID
	StateDigest            []byte
	BindingDigest          []byte
	NonceDigest            []byte
	PkceVerifierCiphertext []byte
	ReturnPath             string
	ExpiresAt              time.Time
	CreatedAt              time.Time
}

func (q *Queries) CreateOIDCAuthTransaction(ctx context.Context, arg CreateOIDCAuthTransactionParams) (IdentityOidcAuthTransaction, error) {
	row := q.db.QueryRow(ctx, createOIDCAuthTransaction,
		arg.ID,
		arg.StateDigest,
		arg.BindingDigest,
		arg.NonceDigest,
		arg.PkceVerifierCiphertext,
		arg.ReturnPath,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i IdentityOidcAuthTransaction
	err := row.Scan(
		&i.ID,
		&i.StateDigest,
		&i.BindingDigest,
		&i.NonceDigest,
		&i.PkceVerifierCiphertext,
		&i.ReturnPath,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOIDCIdentity = `-- name: CreateOIDCIdentity :one
INSERT INTO identity.oidc_identities (id, identity_id, issuer, subject, email, display_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, identity_id, issuer, subject, email, display_name, created_at, updated_at
`

type CreateOIDCIdentityParams struct {
	ID          uuid.UUID
	IdentityID  uuid.UUID
	Issuer      string
	Subject     string
	Email       string
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateOIDCIdentity(ctx context.Context, arg CreateOIDCIdentityParams) (IdentityOidcIdentity, error) {
	row := q.db.QueryRow(ctx, createOIDCIdentity,
		arg.ID,
		arg.IdentityID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IdentityOidcIdentity
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOIDCUserIdentity = `-- name: CreateOIDCUserIdentity :one
INSERT INTO identity.user_identities (id, tenant_eligible, disabled_at, version, created_at, updated_at)
VALUES ($1, true, NULL, 1, $2, $3)
RETURNING id, tenant_eligible, disabled_at, version, created_at, updated_at
`

type CreateOIDCUserIdentityParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateOIDCUserIdentity(ctx context.Context, arg CreateOIDCUserIdentityParams) (IdentityUserIdentity, error) {
	row := q.db.QueryRow(ctx, createOIDCUserIdentity, arg.ID, arg.CreatedAt, arg.UpdatedAt)
	var i IdentityUserIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantEligible,
		&i.DisabledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByDigestForUpdate = `-- name: GetAuthSessionByDigestForUpdate :one
SELECT session.id, session.identity_id, session.token_digest, session.csrf_digest, session.issued_at, session.last_used_at, session.idle_expires_at, session.absolute_expires_at, session.revoked_at, session.version, principal.disabled_at
FROM identity.auth_sessions AS session
JOIN identity.user_identities AS principal ON principal.id = session.identity_id
WHERE session.token_digest = $1
FOR UPDATE OF session, principal
`

type GetAuthSessionByDigestForUpdateRow struct {
	ID                uuid.UUID
	IdentityID        uuid.UUID
	TokenDigest       []byte
	CsrfDigest        []byte
	IssuedAt          time.Time
	LastUsedAt        time.Time
	IdleExpiresAt     time.Time
	AbsoluteExpiresAt time.Time
	RevokedAt         *time.Time
	Version           int64
	DisabledAt        *time.Time
}

func (q *Queries) GetAuthSessionByDigestForUpdate(ctx context.Context, tokenDigest []byte) (GetAuthSessionByDigestForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByDigestForUpdate, tokenDigest)
	var i GetAuthSessionByDigestForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.Version,
		&i.DisabledAt,
	)
	return i, err
}

const getOIDCIdentity = `-- name: GetOIDCIdentity :one
SELECT id, identity_id, issuer, subject, email, display_name, created_at, updated_at FROM identity.oidc_identities WHERE issuer = $1 AND subject = $2
`

type GetOIDCIdentityParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetOIDCIdentity(ctx context.Context, arg GetOIDCIdentityParams) (IdentityOidcIdentity, error) {
	row := q.db.QueryRow(ctx, getOIDCIdentity, arg.Issuer, arg.Subject)
	var i IdentityOidcIdentity
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isLocalAdmin = `-- name: IsLocalAdmin :one
SELECT EXISTS (SELECT 1 FROM identity.local_admins WHERE identity_id = $1)
`

func (q *Queries) IsLocalAdmin(ctx context.Context, identityID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isLocalAdmin, identityID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const loadSessionTenantGrants = `-- name: LoadSessionTenantGrants :many
SELECT membership.tenant_id, binding.role
FROM tenancy.memberships AS membership
JOIN tenancy.role_bindings AS binding
  ON binding.tenant_id = membership.tenant_id AND binding.membership_id = membership.id
JOIN tenancy.tenants AS tenant ON tenant.id = membership.tenant_id
WHERE membership.identity_id = $1
  AND tenant.state = 'active'
ORDER BY membership.tenant_id, binding.role
`

type LoadSessionTenantGrantsRow struct {
	TenantID uuid.UUID
	Role     string
}

func (q *Queries) LoadSessionTenantGrants(ctx context.Context, identityID uuid.UUID) ([]LoadSessionTenantGrantsRow, error) {
	rows, err := q.db.Query(ctx, loadSessionTenantGrants, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadSessionTenantGrantsRow
	for rows.Next() {
		var i LoadSessionTenantGrantsRow
		if err := rows.Scan(&i.TenantID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE identity.auth_sessions
SET revoked_at = $1, version = version + 1
WHERE id = $2 AND revoked_at IS NULL
  AND $1::timestamptz IS NOT NULL
`

type RevokeAuthSessionParams struct {
	RevokedAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAuthSession = `-- name: RotateAuthSession :one
UPDATE identity.auth_sessions
SET token_digest = $1, csrf_digest = $2,
    last_used_at = $3, idle_expires_at = LEAST($4, absolute_expires_at),
    version = version + 1
WHERE id = $5 AND version = $6 AND revoked_at IS NULL
  AND idle_expires_at > $3
  AND absolute_expires_at > $3
RETURNING id, identity_id, token_digest, csrf_digest, issued_at, last_used_at, idle_expires_at, absolute_expires_at, revoked_at, version
`

type RotateAuthSessionParams struct {
	TokenDigest     []byte
	CsrfDigest      []byte
	RotatedAt       time.Time
	IdleExpiresAt   time.Time
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) (IdentityAuthSession, error) {
	row := q.db.QueryRow(ctx, rotateAuthSession,
		arg.TokenDigest,
		arg.CsrfDigest,
		arg.RotatedAt,
		arg.IdleExpiresAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i IdentityAuthSession
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.Version,
	)
	return i, err
}

const touchAuthSession = `-- name: TouchAuthSession :one
UPDATE identity.auth_sessions
SET last_used_at = $1,
    idle_expires_at = LEAST($2, absolute_expires_at),
    version = version + 1
WHERE id = $3 AND version = $4 AND revoked_at IS NULL
  AND idle_expires_at > $1
  AND absolute_expires_at > $1
RETURNING id, identity_id, token_digest, csrf_digest, issued_at, last_used_at, idle_expires_at, absolute_expires_at, revoked_at, version
`

type TouchAuthSessionParams struct {
	LastUsedAt      time.Time
	IdleExpiresAt   time.Time
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) (IdentityAuthSession, error) {
	row := q.db.QueryRow(ctx, touchAuthSession,
		arg.LastUsedAt,
		arg.IdleExpiresAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i IdentityAuthSession
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.TokenDigest,
		&i.CsrfDigest,
		&i.IssuedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.Version,
	)
	return i, err
}

const updateOIDCIdentityProfile = `-- name: UpdateOIDCIdentityProfile :one
UPDATE identity.oidc_identities
SET email = $1, display_name = $2, updated_at = $3
WHERE id = $4
RETURNING id, identity_id, issuer, subject, email, display_name, created_at, updated_at
`

type UpdateOIDCIdentityProfileParams struct {
	Email       string
	DisplayName string
	UpdatedAt   time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateOIDCIdentityProfile(ctx context.Context, arg UpdateOIDCIdentityProfileParams) (IdentityOidcIdentity, error) {
	row := q.db.QueryRow(ctx, updateOIDCIdentityProfile,
		arg.Email,
		arg.DisplayName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i IdentityOidcIdentity
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
