// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_identities.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveServiceTokens = `-- name: CountActiveServiceTokens :one
SELECT count(*) FROM identity.service_tokens
WHERE service_identity_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
`

type CountActiveServiceTokensParams struct {
	ServiceIdentityID uuid.UUID
	Now               time.Time
}

func (q *Queries) CountActiveServiceTokens(ctx context.Context, arg CountActiveServiceTokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveServiceTokens, arg.ServiceIdentityID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceIdentity = `-- name: CreateServiceIdentity :one
INSERT INTO identity.service_identities (id, scope, tenant_id, name, disabled_at, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, NULL, 1, $5, $6)
RETURNING id, scope, tenant_id, scope_key, name, disabled_at, version, created_at, updated_at
`

type CreateServiceIdentityParams struct {
	ID        uuid.UUID
	Scope     string
	TenantID  *uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateServiceIdentity(ctx context.Context, arg CreateServiceIdentityParams) (IdentityServiceIdentity, error) {
	row := q.db.QueryRow(ctx, createServiceIdentity,
		arg.ID,
		arg.Scope,
		arg.TenantID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i IdentityServiceIdentity
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Name,
		&i.DisabledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceToken = `-- name: CreateServiceToken :one
INSERT INTO identity.service_tokens (
    id, service_identity_id, scope, tenant_id, prefix, verifier, role, source_cidr,
    expires_at, revoked_at, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, NULL, $10
)
RETURNING id, service_identity_id, scope, tenant_id, scope_key, prefix, verifier, role, source_cidr, expires_at, revoked_at, created_at
`

type CreateServiceTokenParams struct {
	ID                uuid.UUID
	ServiceIdentityID uuid.UUID
	Scope             string
	TenantID          *uuid.UUID
	Prefix            string
	Verifier          string
	Role              string
	SourceCidr        *netip.Prefix
	ExpiresAt         time.Time
	CreatedAt         time.Time
}

func (q *Queries) CreateServiceToken(ctx context.Context, arg CreateServiceTokenParams) (IdentityServiceToken, error) {
	row := q.db.QueryRow(ctx, createServiceToken,
		arg.ID,
		arg.ServiceIdentityID,
		arg.Scope,
		arg.TenantID,
		arg.Prefix,
		arg.Verifier,
		arg.Role,
		arg.SourceCidr,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i IdentityServiceToken
	err := row.Scan(
		&i.ID,
		&i.ServiceIdentityID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Prefix,
		&i.Verifier,
		&i.Role,
		&i.SourceCidr,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const disableServiceIdentity = `-- name: DisableServiceIdentity :one
UPDATE identity.service_identities
SET disabled_at = $1::timestamptz, updated_at = $2, version = version + 1
WHERE id = $3 AND version = $4 AND disabled_at IS NULL
RETURNING id, scope, tenant_id, scope_key, name, disabled_at, version, created_at, updated_at
`

type DisableServiceIdentityParams struct {
	DisabledAt      time.Time
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) DisableServiceIdentity(ctx context.Context, arg DisableServiceIdentityParams) (IdentityServiceIdentity, error) {
	row := q.db.QueryRow(ctx, disableServiceIdentity,
		arg.DisabledAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i IdentityServiceIdentity
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Name,
		&i.DisabledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findServiceTokenCandidates = `-- name: FindServiceTokenCandidates :many
SELECT token.id, token.service_identity_id, token.scope, token.tenant_id, token.scope_key, token.prefix, token.verifier, token.role, token.source_cidr, token.expires_at, token.revoked_at, token.created_at, principal.name AS service_identity_name, principal.disabled_at AS service_identity_disabled_at
FROM identity.service_tokens AS token
JOIN identity.service_identities AS principal ON principal.id = token.service_identity_id
WHERE token.prefix = $1
  AND token.scope = $2
  AND token.tenant_id IS NOT DISTINCT FROM $3::uuid
ORDER BY token.created_at DESC, token.id
LIMIT 8
`

type FindServiceTokenCandidatesParams struct {
	Prefix   string
	Scope    string
	TenantID *uuid.UUID
}

type FindServiceTokenCandidatesRow struct {
	ID                        uuid.UUID
	ServiceIdentityID         uuid.UUID
	Scope                     string
	TenantID                  *uuid.UUID
	ScopeKey                  *uuid.UUID
	Prefix                    string
	Verifier                  string
	Role                      string
	SourceCidr                *netip.Prefix
	ExpiresAt                 time.Time
	RevokedAt                 *time.Time
	CreatedAt                 time.Time
	ServiceIdentityName       string
	ServiceIdentityDisabledAt *time.Time
}

func (q *Queries) FindServiceTokenCandidates(ctx context.Context, arg FindServiceTokenCandidatesParams) ([]FindServiceTokenCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findServiceTokenCandidates, arg.Prefix, arg.Scope, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindServiceTokenCandidatesRow
	for rows.Next() {
		var i FindServiceTokenCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceIdentityID,
			&i.Scope,
			&i.TenantID,
			&i.ScopeKey,
			&i.Prefix,
			&i.Verifier,
			&i.Role,
			&i.SourceCidr,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.ServiceIdentityName,
			&i.ServiceIdentityDisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceIdentity = `-- name: GetServiceIdentity :one
SELECT id, scope, tenant_id, scope_key, name, disabled_at, version, created_at, updated_at FROM identity.service_identities WHERE id = $1
`

func (q *Queries) GetServiceIdentity(ctx context.Context, id uuid.UUID) (IdentityServiceIdentity, error) {
	row := q.db.QueryRow(ctx, getServiceIdentity, id)
	var i IdentityServiceIdentity
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Name,
		&i.DisabledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceIdentityForAuthentication = `-- name: GetServiceIdentityForAuthentication :one
SELECT id, scope, tenant_id, scope_key, name, disabled_at, version, created_at, updated_at FROM identity.service_identities
WHERE id = $1
FOR SHARE
`

func (q *Queries) GetServiceIdentityForAuthentication(ctx context.Context, id uuid.UUID) (IdentityServiceIdentity, error) {
	row := q.db.QueryRow(ctx, getServiceIdentityForAuthentication, id)
	var i IdentityServiceIdentity
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Name,
		&i.DisabledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceIdentityForUpdate = `-- name: GetServiceIdentityForUpdate :one
SELECT id, scope, tenant_id, scope_key, name, disabled_at, version, created_at, updated_at FROM identity.service_identities WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetServiceIdentityForUpdate(ctx context.Context, id uuid.UUID) (IdentityServiceIdentity, error) {
	row := q.db.QueryRow(ctx, getServiceIdentityForUpdate, id)
	var i IdentityServiceIdentity
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Name,
		&i.DisabledAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceTokenForAuthentication = `-- name: GetServiceTokenForAuthentication :one
SELECT token.id, token.service_identity_id, token.scope, token.tenant_id, token.scope_key, token.prefix, token.verifier, token.role, token.source_cidr, token.expires_at, token.revoked_at, token.created_at
FROM identity.service_tokens AS token
WHERE token.id = $1
  AND token.service_identity_id = $2
  AND token.scope = $3
  AND token.tenant_id IS NOT DISTINCT FROM $4::uuid
FOR SHARE OF token
`

type GetServiceTokenForAuthenticationParams struct {
	ID                uuid.UUID
	ServiceIdentityID uuid.UUID
	Scope             string
	TenantID          *uuid.UUID
}

func (q *Queries) GetServiceTokenForAuthentication(ctx context.Context, arg GetServiceTokenForAuthenticationParams) (IdentityServiceToken, error) {
	row := q.db.QueryRow(ctx, getServiceTokenForAuthentication,
		arg.ID,
		arg.ServiceIdentityID,
		arg.Scope,
		arg.TenantID,
	)
	var i IdentityServiceToken
	err := row.Scan(
		&i.ID,
		&i.ServiceIdentityID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Prefix,
		&i.Verifier,
		&i.Role,
		&i.SourceCidr,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listServiceIdentities = `-- name: ListServiceIdentities :many
SELECT id, scope, tenant_id, scope_key, name, disabled_at, version, created_at, updated_at FROM identity.service_identities
WHERE ($1::text IS NULL OR scope = $1)
  AND ($2::uuid IS NULL OR tenant_id = $2)
  AND (created_at, id) > ($3::timestamptz, $4::uuid)
ORDER BY created_at, id
LIMIT $5
`

type ListServiceIdentitiesParams struct {
	Scope          pgtype.Text
	TenantID       *uuid.UUID
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

func (q *Queries) ListServiceIdentities(ctx context.Context, arg ListServiceIdentitiesParams) ([]IdentityServiceIdentity, error) {
	rows, err := q.db.Query(ctx, listServiceIdentities,
		arg.Scope,
		arg.TenantID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityServiceIdentity
	for rows.Next() {
		var i IdentityServiceIdentity
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.TenantID,
			&i.ScopeKey,
			&i.Name,
			&i.DisabledAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTokens = `-- name: ListServiceTokens :many
SELECT id, service_identity_id, scope, tenant_id, prefix, role, source_cidr, expires_at, revoked_at, created_at
FROM identity.service_tokens
WHERE service_identity_id = $1
ORDER BY created_at, id
`

type ListServiceTokensRow struct {
	ID                uuid.UUID
	ServiceIdentityID uuid.UUID
	Scope             string
	TenantID          *uuid.UUID
	Prefix            string
	Role              string
	SourceCidr        *netip.Prefix
	ExpiresAt         time.Time
	RevokedAt         *time.Time
	CreatedAt         time.Time
}

func (q *Queries) ListServiceTokens(ctx context.Context, serviceIdentityID uuid.UUID) ([]ListServiceTokensRow, error) {
	rows, err := q.db.Query(ctx, listServiceTokens, serviceIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceTokensRow
	for rows.Next() {
		var i ListServiceTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceIdentityID,
			&i.Scope,
			&i.TenantID,
			&i.Prefix,
			&i.Role,
			&i.SourceCidr,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeActiveServiceIdentityTokens = `-- name: RevokeActiveServiceIdentityTokens :execrows
UPDATE identity.service_tokens
SET revoked_at = $1::timestamptz
WHERE service_identity_id = $2
  AND revoked_at IS NULL
`

type RevokeActiveServiceIdentityTokensParams struct {
	RevokedAt         time.Time
	ServiceIdentityID uuid.UUID
}

func (q *Queries) RevokeActiveServiceIdentityTokens(ctx context.Context, arg RevokeActiveServiceIdentityTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveServiceIdentityTokens, arg.RevokedAt, arg.ServiceIdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeServiceToken = `-- name: RevokeServiceToken :one
UPDATE identity.service_tokens
SET revoked_at = $1::timestamptz
WHERE id = $2 AND revoked_at IS NULL
RETURNING id, service_identity_id, scope, tenant_id, scope_key, prefix, verifier, role, source_cidr, expires_at, revoked_at, created_at
`

type RevokeServiceTokenParams struct {
	RevokedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) RevokeServiceToken(ctx context.Context, arg RevokeServiceTokenParams) (IdentityServiceToken, error) {
	row := q.db.QueryRow(ctx, revokeServiceToken, arg.RevokedAt, arg.ID)
	var i IdentityServiceToken
	err := row.Scan(
		&i.ID,
		&i.ServiceIdentityID,
		&i.Scope,
		&i.TenantID,
		&i.ScopeKey,
		&i.Prefix,
		&i.Verifier,
		&i.Role,
		&i.SourceCidr,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
