// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getEnrollmentByPrefix = `-- name: GetEnrollmentByPrefix :one
SELECT id, expected_node_name, token_prefix, token_verifier, created_by, expires_at, consumed_at, consumed_node_id, revoked_at, created_at FROM nodes.node_enrollments WHERE token_prefix = $1 AND consumed_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) GetEnrollmentByPrefix(ctx context.Context, tokenPrefix string) (NodesNodeEnrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByPrefix, tokenPrefix)
	var i NodesNodeEnrollment
	err := row.Scan(
		&i.ID,
		&i.ExpectedNodeName,
		&i.TokenPrefix,
		&i.TokenVerifier,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedNodeID,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, name, normalized_name, desired_labels, observed_labels, max_runners, reserved_headroom, active_runners, maintenance_state, connectivity_state, architecture, agent_version, runtime_capabilities, last_heartbeat_at, session_generation, version, created_at, updated_at FROM nodes.nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (NodesNode, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i NodesNode
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.DesiredLabels,
		&i.ObservedLabels,
		&i.MaxRunners,
		&i.ReservedHeadroom,
		&i.ActiveRunners,
		&i.MaintenanceState,
		&i.ConnectivityState,
		&i.Architecture,
		&i.AgentVersion,
		&i.RuntimeCapabilities,
		&i.LastHeartbeatAt,
		&i.SessionGeneration,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByPrefix = `-- name: GetSessionByPrefix :one
SELECT id, node_id, agent_instance_id, token_prefix, token_verifier, protocol_revision, session_generation, expires_at, revoked_at, created_at, last_used_at FROM nodes.node_sessions WHERE token_prefix = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSessionByPrefix(ctx context.Context, tokenPrefix string) (NodesNodeSession, error) {
	row := q.db.QueryRow(ctx, getSessionByPrefix, tokenPrefix)
	var i NodesNodeSession
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.AgentInstanceID,
		&i.TokenPrefix,
		&i.TokenVerifier,
		&i.ProtocolRevision,
		&i.SessionGeneration,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, normalized_name, desired_labels, observed_labels, max_runners, reserved_headroom, active_runners, maintenance_state, connectivity_state, architecture, agent_version, runtime_capabilities, last_heartbeat_at, session_generation, version, created_at, updated_at FROM nodes.nodes WHERE (created_at,id) > ($1,$2) ORDER BY created_at,id LIMIT $3
`

type ListNodesParams struct {
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]NodesNode, error) {
	rows, err := q.db.Query(ctx, listNodes, arg.CreatedAt, arg.CreatedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodesNode
	for rows.Next() {
		var i NodesNode
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.DesiredLabels,
			&i.ObservedLabels,
			&i.MaxRunners,
			&i.ReservedHeadroom,
			&i.ActiveRunners,
			&i.MaintenanceState,
			&i.ConnectivityState,
			&i.Architecture,
			&i.AgentVersion,
			&i.RuntimeCapabilities,
			&i.LastHeartbeatAt,
			&i.SessionGeneration,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
