// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountsAccount struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	Name                string
	NormalizedName      string
	State               string
	Health              string
	MembershipID        pgtype.Text
	MembershipExpiresAt *time.Time
	Labels              []byte
	MaxConcurrency      int32
	HealthSuccesses     int32
	HealthFailures      int32
	LastHealthAt        *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type AccountsAccountCapacityReservation struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	AccountID uuid.UUID
	OwnerID   uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type AccountsAccountCredential struct {
	TenantID    uuid.UUID
	AccountID   uuid.UUID
	Version     int64
	Provider    string
	KeyID       string
	Ciphertext  []byte
	WrappedDek  []byte
	ExternalRef string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
	RetiredAt   *time.Time
}

type EndpointsAccessProfile struct {
	TenantID              uuid.UUID
	EndpointID            uuid.UUID
	Protocols             []string
	DnsMode               string
	SourceCidrs           []byte
	TargetAllowCidrs      []byte
	TargetDenyCidrs       []byte
	TargetAllowDomains    []byte
	TargetDenyDomains     []byte
	AllowedPorts          []byte
	PolicyDocument        []byte
	PolicyHash            string
	MaxConnections        int32
	MaxConnectionRate     int32
	IdleTimeoutSeconds    int32
	MaxBytesPerConnection int64
	TrafficWindowSeconds  int32
	MaxWindowBytes        int64
	Version               int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type EndpointsEndpointStatus struct {
	TenantID               uuid.UUID
	EndpointID             uuid.UUID
	ObservedGeneration     int64
	ObservedState          string
	RunnerID               *uuid.UUID
	ReasonCode             string
	LastAgentObservationAt *time.Time
	LastTransitionAt       time.Time
	UpdatedAt              time.Time
}

type EndpointsProxyCredential struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	EndpointID       uuid.UUID
	PublicIdentifier string
	Verifier         string
	ExpiresAt        *time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type EndpointsProxyEndpoint struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	Name               string
	NormalizedName     string
	BindingMode        string
	AccountID          *uuid.UUID
	NodeID             *uuid.UUID
	DesiredRunnerState string
	LifecycleState     string
	DesiredGeneration  int64
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	PoolID             *uuid.UUID
}

type GatewaysEnrollment struct {
	ID                     uuid.UUID
	ExpectedGatewayName    string
	TokenPrefix            string
	TokenVerifier          string
	CertificateFingerprint string
	CreatedBy              uuid.UUID
	ExpiresAt              time.Time
	ConsumedAt             *time.Time
	ConsumedGatewayID      *uuid.UUID
	RevokedAt              *time.Time
	CreatedAt              time.Time
}

type GatewaysGateway struct {
	ID                     uuid.UUID
	Name                   string
	NormalizedName         string
	CertificateFingerprint string
	State                  string
	ConnectivityState      string
	GatewayVersion         string
	Architecture           string
	LastHeartbeatAt        *time.Time
	SessionGeneration      int64
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type GatewaysRouteGrant struct {
	GatewayID         uuid.UUID
	TenantID          uuid.UUID
	EndpointID        uuid.UUID
	RunnerID          uuid.UUID
	DesiredGeneration int64
	PolicyHash        string
	ExpiresAt         time.Time
	Signature         []byte
	CreatedAt         time.Time
}

type GatewaysSession struct {
	ID                uuid.UUID
	GatewayID         uuid.UUID
	GatewayInstanceID uuid.UUID
	TokenPrefix       string
	TokenVerifier     string
	ProtocolRevision  int32
	SessionGeneration int64
	ExpiresAt         time.Time
	RevokedAt         *time.Time
	CreatedAt         time.Time
	LastUsedAt        *time.Time
}

type GatewaysUsageWindow struct {
	TenantID          uuid.UUID
	EndpointID        uuid.UUID
	CredentialID      uuid.UUID
	WindowStart       time.Time
	WindowSeconds     int32
	ActiveConnections int32
	ConnectionCount   int64
	BytesIn           int64
	BytesOut          int64
	Version           int64
	UpdatedAt         time.Time
}

type NodesNode struct {
	ID                  uuid.UUID
	Name                string
	NormalizedName      string
	DesiredLabels       []byte
	ObservedLabels      []byte
	MaxRunners          int32
	ReservedHeadroom    int32
	ActiveRunners       int32
	MaintenanceState    string
	ConnectivityState   string
	Architecture        string
	AgentVersion        string
	RuntimeCapabilities []byte
	LastHeartbeatAt     *time.Time
	SessionGeneration   int64
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type NodesNodeEnrollment struct {
	ID               uuid.UUID
	ExpectedNodeName string
	TokenPrefix      string
	TokenVerifier    string
	CreatedBy        uuid.UUID
	ExpiresAt        time.Time
	ConsumedAt       *time.Time
	ConsumedNodeID   *uuid.UUID
	RevokedAt        *time.Time
	CreatedAt        time.Time
}

type NodesNodeSession struct {
	ID                uuid.UUID
	NodeID            uuid.UUID
	AgentInstanceID   uuid.UUID
	TokenPrefix       string
	TokenVerifier     string
	ProtocolRevision  int32
	SessionGeneration int64
	ExpiresAt         time.Time
	RevokedAt         *time.Time
	CreatedAt         time.Time
	LastUsedAt        *time.Time
}

type OperationsOperation struct {
	ID                  uuid.UUID
	TenantID            *uuid.UUID
	OperationType       string
	ResourceType        string
	ResourceID          uuid.UUID
	RequestedGeneration int64
	State               string
	Attempts            int32
	ProgressCategory    string
	ResultCode          string
	SafeMessage         string
	RequestedBy         uuid.UUID
	StartedAt           *time.Time
	CompletedAt         *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type PoolsAccountPool struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	NormalizedName string
	Strategy       string
	Selector       []byte
	State          string
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PoolsAccountPoolMembership struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	PoolID    uuid.UUID
	AccountID uuid.UUID
	Priority  int32
	Weight    int32
	Enabled   bool
	ExpiresAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ReconcilerFinalizer struct {
	TenantID     uuid.UUID
	ResourceType string
	ResourceID   uuid.UUID
	Finalizer    string
	CreatedAt    time.Time
}

type ReconcilerRunnerDesiredState struct {
	TenantID              uuid.UUID
	EndpointID            uuid.UUID
	RunnerID              uuid.UUID
	NodeID                uuid.UUID
	AccountID             uuid.UUID
	CredentialVersion     int64
	DesiredGeneration     int64
	DesiredAction         string
	OperationID           uuid.UUID
	CapacityReservationID *uuid.UUID
	RuntimeSpec           []byte
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type ReconcilerRunnerObservation struct {
	RunnerID           uuid.UUID
	TenantID           uuid.UUID
	EndpointID         uuid.UUID
	NodeID             uuid.UUID
	OperationID        uuid.UUID
	ObservedGeneration int64
	ObservedState      string
	RuntimeID          string
	ReasonCode         string
	RestartCount       int32
	ObservedAt         time.Time
	UpdatedAt          time.Time
}

type ReconcilerWorkItem struct {
	ID             uuid.UUID
	TenantID       *uuid.UUID
	ResourceType   string
	ResourceID     uuid.UUID
	Action         string
	Generation     int64
	OperationID    uuid.UUID
	AvailableAt    time.Time
	LeaseOwner     *uuid.UUID
	LeaseDeadline  *time.Time
	Attempts       int32
	LastResultCode string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type SchedulerEndpointAssignment struct {
	TenantID              uuid.UUID
	EndpointID            uuid.UUID
	AssignmentID          uuid.UUID
	PoolID                *uuid.UUID
	AccountID             *uuid.UUID
	NodeID                *uuid.UUID
	RunnerID              *uuid.UUID
	CapacityReservationID *uuid.UUID
	DesiredGeneration     int64
	FencingToken          int64
	Strategy              string
	State                 string
	HealthState           string
	RetryAttempts         int32
	CooldownUntil         *time.Time
	ValidUntil            *time.Time
	LastReasonCode        string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type SchedulerHealthObservation struct {
	TenantID             uuid.UUID
	ResourceType         string
	ResourceID           uuid.UUID
	Dimension            string
	State                string
	Generation           int64
	LastSequence         int64
	ConsecutiveSuccesses int32
	ConsecutiveFailures  int32
	ReasonCode           string
	CooldownUntil        *time.Time
	LastObservedAt       *time.Time
	LastTransitionAt     time.Time
	UpdatedAt            time.Time
}

type SchedulerMigrationAttempt struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	EndpointID      uuid.UUID
	AssignmentID    uuid.UUID
	OperationID     uuid.UUID
	MigrationType   string
	SourceAccountID *uuid.UUID
	SourceNodeID    *uuid.UUID
	TargetAccountID *uuid.UUID
	TargetNodeID    *uuid.UUID
	FencingToken    int64
	Attempt         int32
	State           string
	ResultCode      string
	CooldownUntil   *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SchedulerPoolCursor struct {
	TenantID     uuid.UUID
	PoolID       uuid.UUID
	Cursor       int64
	FencingToken int64
	Version      int64
	UpdatedAt    time.Time
}

type TenancyMembership struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	IdentityID uuid.UUID
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TenancyRoleBinding struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	MembershipID uuid.UUID
	Role         string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TenancyTenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	State     string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenancyTenantQuota struct {
	TenantID           uuid.UUID
	MaxAccounts        int32
	MaxPools           int32
	MaxPoolMemberships int32
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
