// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduler.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advancePoolCursorWithFence = `-- name: AdvancePoolCursorWithFence :one
INSERT INTO scheduler.pool_cursors (tenant_id,pool_id,cursor,fencing_token,version,updated_at) VALUES ($1,$2,$3,$4,1,$5)
ON CONFLICT (tenant_id,pool_id) DO UPDATE SET cursor=EXCLUDED.cursor,fencing_token=EXCLUDED.fencing_token,version=scheduler.pool_cursors.version+1,updated_at=EXCLUDED.updated_at
WHERE scheduler.pool_cursors.fencing_token <= EXCLUDED.fencing_token
RETURNING tenant_id, pool_id, cursor, fencing_token, version, updated_at
`

type AdvancePoolCursorWithFenceParams struct {
	TenantID     uuid.UUID
	PoolID       uuid.UUID
	Cursor       int64
	FencingToken int64
	UpdatedAt    time.Time
}

func (q *Queries) AdvancePoolCursorWithFence(ctx context.Context, arg AdvancePoolCursorWithFenceParams) (SchedulerPoolCursor, error) {
	row := q.db.QueryRow(ctx, advancePoolCursorWithFence,
		arg.TenantID,
		arg.PoolID,
		arg.Cursor,
		arg.FencingToken,
		arg.UpdatedAt,
	)
	var i SchedulerPoolCursor
	err := row.Scan(
		&i.TenantID,
		&i.PoolID,
		&i.Cursor,
		&i.FencingToken,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointAssignment = `-- name: GetEndpointAssignment :one
SELECT tenant_id, endpoint_id, assignment_id, pool_id, account_id, node_id, runner_id, capacity_reservation_id, desired_generation, fencing_token, strategy, state, health_state, retry_attempts, cooldown_until, valid_until, last_reason_code, created_at, updated_at FROM scheduler.endpoint_assignments WHERE tenant_id=$1 AND endpoint_id=$2
`

type GetEndpointAssignmentParams struct {
	TenantID   uuid.UUID
	EndpointID uuid.UUID
}

func (q *Queries) GetEndpointAssignment(ctx context.Context, arg GetEndpointAssignmentParams) (SchedulerEndpointAssignment, error) {
	row := q.db.QueryRow(ctx, getEndpointAssignment, arg.TenantID, arg.EndpointID)
	var i SchedulerEndpointAssignment
	err := row.Scan(
		&i.TenantID,
		&i.EndpointID,
		&i.AssignmentID,
		&i.PoolID,
		&i.AccountID,
		&i.NodeID,
		&i.RunnerID,
		&i.CapacityReservationID,
		&i.DesiredGeneration,
		&i.FencingToken,
		&i.Strategy,
		&i.State,
		&i.HealthState,
		&i.RetryAttempts,
		&i.CooldownUntil,
		&i.ValidUntil,
		&i.LastReasonCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHealthObservation = `-- name: GetHealthObservation :one
SELECT tenant_id, resource_type, resource_id, dimension, state, generation, last_sequence, consecutive_successes, consecutive_failures, reason_code, cooldown_until, last_observed_at, last_transition_at, updated_at FROM scheduler.health_observations WHERE tenant_id=$1 AND resource_type=$2 AND resource_id=$3 AND dimension=$4
`

type GetHealthObservationParams struct {
	TenantID     uuid.UUID
	ResourceType string
	ResourceID   uuid.UUID
	Dimension    string
}

func (q *Queries) GetHealthObservation(ctx context.Context, arg GetHealthObservationParams) (SchedulerHealthObservation, error) {
	row := q.db.QueryRow(ctx, getHealthObservation,
		arg.TenantID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Dimension,
	)
	var i SchedulerHealthObservation
	err := row.Scan(
		&i.TenantID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Dimension,
		&i.State,
		&i.Generation,
		&i.LastSequence,
		&i.ConsecutiveSuccesses,
		&i.ConsecutiveFailures,
		&i.ReasonCode,
		&i.CooldownUntil,
		&i.LastObservedAt,
		&i.LastTransitionAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPoolCursor = `-- name: GetPoolCursor :one
SELECT tenant_id, pool_id, cursor, fencing_token, version, updated_at FROM scheduler.pool_cursors WHERE tenant_id=$1 AND pool_id=$2
`

type GetPoolCursorParams struct {
	TenantID uuid.UUID
	PoolID   uuid.UUID
}

func (q *Queries) GetPoolCursor(ctx context.Context, arg GetPoolCursorParams) (SchedulerPoolCursor, error) {
	row := q.db.QueryRow(ctx, getPoolCursor, arg.TenantID, arg.PoolID)
	var i SchedulerPoolCursor
	err := row.Scan(
		&i.TenantID,
		&i.PoolID,
		&i.Cursor,
		&i.FencingToken,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentsByState = `-- name: ListAssignmentsByState :many
SELECT tenant_id, endpoint_id, assignment_id, pool_id, account_id, node_id, runner_id, capacity_reservation_id, desired_generation, fencing_token, strategy, state, health_state, retry_attempts, cooldown_until, valid_until, last_reason_code, created_at, updated_at FROM scheduler.endpoint_assignments WHERE state=$1 ORDER BY updated_at,tenant_id,endpoint_id LIMIT $2
`

type ListAssignmentsByStateParams struct {
	State string
	Limit int32
}

func (q *Queries) ListAssignmentsByState(ctx context.Context, arg ListAssignmentsByStateParams) ([]SchedulerEndpointAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByState, arg.State, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerEndpointAssignment
	for rows.Next() {
		var i SchedulerEndpointAssignment
		if err := rows.Scan(
			&i.TenantID,
			&i.EndpointID,
			&i.AssignmentID,
			&i.PoolID,
			&i.AccountID,
			&i.NodeID,
			&i.RunnerID,
			&i.CapacityReservationID,
			&i.DesiredGeneration,
			&i.FencingToken,
			&i.Strategy,
			&i.State,
			&i.HealthState,
			&i.RetryAttempts,
			&i.CooldownUntil,
			&i.ValidUntil,
			&i.LastReasonCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHealthByState = `-- name: ListHealthByState :many
SELECT tenant_id, resource_type, resource_id, dimension, state, generation, last_sequence, consecutive_successes, consecutive_failures, reason_code, cooldown_until, last_observed_at, last_transition_at, updated_at FROM scheduler.health_observations WHERE state=$1 ORDER BY updated_at,tenant_id,resource_type,resource_id LIMIT $2
`

type ListHealthByStateParams struct {
	State string
	Limit int32
}

func (q *Queries) ListHealthByState(ctx context.Context, arg ListHealthByStateParams) ([]SchedulerHealthObservation, error) {
	rows, err := q.db.Query(ctx, listHealthByState, arg.State, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerHealthObservation
	for rows.Next() {
		var i SchedulerHealthObservation
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Dimension,
			&i.State,
			&i.Generation,
			&i.LastSequence,
			&i.ConsecutiveSuccesses,
			&i.ConsecutiveFailures,
			&i.ReasonCode,
			&i.CooldownUntil,
			&i.LastObservedAt,
			&i.LastTransitionAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationAttempts = `-- name: ListMigrationAttempts :many
SELECT id, tenant_id, endpoint_id, assignment_id, operation_id, migration_type, source_account_id, source_node_id, target_account_id, target_node_id, fencing_token, attempt, state, result_code, cooldown_until, created_at, updated_at FROM scheduler.migration_attempts WHERE tenant_id=$1 AND endpoint_id=$2 ORDER BY created_at,id
`

type ListMigrationAttemptsParams struct {
	TenantID   uuid.UUID
	EndpointID uuid.UUID
}

func (q *Queries) ListMigrationAttempts(ctx context.Context, arg ListMigrationAttemptsParams) ([]SchedulerMigrationAttempt, error) {
	rows, err := q.db.Query(ctx, listMigrationAttempts, arg.TenantID, arg.EndpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerMigrationAttempt
	for rows.Next() {
		var i SchedulerMigrationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.AssignmentID,
			&i.OperationID,
			&i.MigrationType,
			&i.SourceAccountID,
			&i.SourceNodeID,
			&i.TargetAccountID,
			&i.TargetNodeID,
			&i.FencingToken,
			&i.Attempt,
			&i.State,
			&i.ResultCode,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignmentStateWithFence = `-- name: UpdateAssignmentStateWithFence :one
UPDATE scheduler.endpoint_assignments SET state=$4,health_state=$5,retry_attempts=$6,cooldown_until=$7,valid_until=$8,last_reason_code=$9,fencing_token=$3,updated_at=$10
WHERE tenant_id=$1 AND endpoint_id=$2 AND fencing_token <= $3
RETURNING tenant_id, endpoint_id, assignment_id, pool_id, account_id, node_id, runner_id, capacity_reservation_id, desired_generation, fencing_token, strategy, state, health_state, retry_attempts, cooldown_until, valid_until, last_reason_code, created_at, updated_at
`

type UpdateAssignmentStateWithFenceParams struct {
	TenantID       uuid.UUID
	EndpointID     uuid.UUID
	FencingToken   int64
	State          string
	HealthState    string
	RetryAttempts  int32
	CooldownUntil  *time.Time
	ValidUntil     *time.Time
	LastReasonCode string
	UpdatedAt      time.Time
}

func (q *Queries) UpdateAssignmentStateWithFence(ctx context.Context, arg UpdateAssignmentStateWithFenceParams) (SchedulerEndpointAssignment, error) {
	row := q.db.QueryRow(ctx, updateAssignmentStateWithFence,
		arg.TenantID,
		arg.EndpointID,
		arg.FencingToken,
		arg.State,
		arg.HealthState,
		arg.RetryAttempts,
		arg.CooldownUntil,
		arg.ValidUntil,
		arg.LastReasonCode,
		arg.UpdatedAt,
	)
	var i SchedulerEndpointAssignment
	err := row.Scan(
		&i.TenantID,
		&i.EndpointID,
		&i.AssignmentID,
		&i.PoolID,
		&i.AccountID,
		&i.NodeID,
		&i.RunnerID,
		&i.CapacityReservationID,
		&i.DesiredGeneration,
		&i.FencingToken,
		&i.Strategy,
		&i.State,
		&i.HealthState,
		&i.RetryAttempts,
		&i.CooldownUntil,
		&i.ValidUntil,
		&i.LastReasonCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
