// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateway_usage.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUsageWindow = `-- name: GetUsageWindow :one
SELECT tenant_id, endpoint_id, credential_id, window_start, window_seconds, active_connections, connection_count, bytes_in, bytes_out, version, updated_at FROM gateways.usage_windows WHERE tenant_id=$1 AND endpoint_id=$2 AND credential_id=$3 AND window_start=$4
`

type GetUsageWindowParams struct {
	TenantID     uuid.UUID
	EndpointID   uuid.UUID
	CredentialID uuid.UUID
	WindowStart  time.Time
}

func (q *Queries) GetUsageWindow(ctx context.Context, arg GetUsageWindowParams) (GatewaysUsageWindow, error) {
	row := q.db.QueryRow(ctx, getUsageWindow,
		arg.TenantID,
		arg.EndpointID,
		arg.CredentialID,
		arg.WindowStart,
	)
	var i GatewaysUsageWindow
	err := row.Scan(
		&i.TenantID,
		&i.EndpointID,
		&i.CredentialID,
		&i.WindowStart,
		&i.WindowSeconds,
		&i.ActiveConnections,
		&i.ConnectionCount,
		&i.BytesIn,
		&i.BytesOut,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
