// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciler.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRunnerDesiredState = `-- name: GetRunnerDesiredState :one
SELECT tenant_id, endpoint_id, runner_id, node_id, account_id, credential_version, desired_generation, desired_action, operation_id, capacity_reservation_id, runtime_spec, created_at, updated_at FROM reconciler.runner_desired_states WHERE tenant_id=$1 AND endpoint_id=$2
`

type GetRunnerDesiredStateParams struct {
	TenantID   uuid.UUID
	EndpointID uuid.UUID
}

func (q *Queries) GetRunnerDesiredState(ctx context.Context, arg GetRunnerDesiredStateParams) (ReconcilerRunnerDesiredState, error) {
	row := q.db.QueryRow(ctx, getRunnerDesiredState, arg.TenantID, arg.EndpointID)
	var i ReconcilerRunnerDesiredState
	err := row.Scan(
		&i.TenantID,
		&i.EndpointID,
		&i.RunnerID,
		&i.NodeID,
		&i.AccountID,
		&i.CredentialVersion,
		&i.DesiredGeneration,
		&i.DesiredAction,
		&i.OperationID,
		&i.CapacityReservationID,
		&i.RuntimeSpec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseWorkItems = `-- name: LeaseWorkItems :many
WITH candidates AS (
  SELECT id FROM reconciler.work_items
  WHERE available_at <= $1 AND (lease_owner IS NULL OR lease_deadline <= $1)
  ORDER BY available_at,created_at,id
  FOR UPDATE SKIP LOCKED LIMIT $2
)
UPDATE reconciler.work_items w SET lease_owner=$3,lease_deadline=$4,attempts=w.attempts+1,updated_at=$1
FROM candidates c WHERE w.id=c.id RETURNING w.id, w.tenant_id, w.resource_type, w.resource_id, w.action, w.generation, w.operation_id, w.available_at, w.lease_owner, w.lease_deadline, w.attempts, w.last_result_code, w.created_at, w.updated_at
`

type LeaseWorkItemsParams struct {
	UpdatedAt     time.Time
	Limit         int32
	LeaseOwner    *uuid.UUID
	LeaseDeadline *time.Time
}

func (q *Queries) LeaseWorkItems(ctx context.Context, arg LeaseWorkItemsParams) ([]ReconcilerWorkItem, error) {
	rows, err := q.db.Query(ctx, leaseWorkItems,
		arg.UpdatedAt,
		arg.Limit,
		arg.LeaseOwner,
		arg.LeaseDeadline,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconcilerWorkItem
	for rows.Next() {
		var i ReconcilerWorkItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Generation,
			&i.OperationID,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseDeadline,
			&i.Attempts,
			&i.LastResultCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
