// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getEndpoint = `-- name: GetEndpoint :one
SELECT e.id, e.tenant_id, e.name, e.normalized_name, e.binding_mode, e.account_id, e.node_id, e.desired_runner_state, e.lifecycle_state, e.desired_generation, e.version, e.created_at, e.updated_at, s.observed_generation, s.observed_state, s.runner_id, s.reason_code,
       s.last_agent_observation_at, s.last_transition_at
FROM endpoints.proxy_endpoints e
JOIN endpoints.endpoint_status s ON s.tenant_id=e.tenant_id AND s.endpoint_id=e.id
WHERE e.tenant_id=$1 AND e.id=$2
`

type GetEndpointParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetEndpointRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	Name                   string
	NormalizedName         string
	BindingMode            string
	AccountID              uuid.UUID
	NodeID                 uuid.UUID
	DesiredRunnerState     string
	LifecycleState         string
	DesiredGeneration      int64
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ObservedGeneration     int64
	ObservedState          string
	RunnerID               *uuid.UUID
	ReasonCode             string
	LastAgentObservationAt *time.Time
	LastTransitionAt       time.Time
}

func (q *Queries) GetEndpoint(ctx context.Context, arg GetEndpointParams) (GetEndpointRow, error) {
	row := q.db.QueryRow(ctx, getEndpoint, arg.TenantID, arg.ID)
	var i GetEndpointRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NormalizedName,
		&i.BindingMode,
		&i.AccountID,
		&i.NodeID,
		&i.DesiredRunnerState,
		&i.LifecycleState,
		&i.DesiredGeneration,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedGeneration,
		&i.ObservedState,
		&i.RunnerID,
		&i.ReasonCode,
		&i.LastAgentObservationAt,
		&i.LastTransitionAt,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT e.id, e.tenant_id, e.name, e.normalized_name, e.binding_mode, e.account_id, e.node_id, e.desired_runner_state, e.lifecycle_state, e.desired_generation, e.version, e.created_at, e.updated_at, s.observed_generation, s.observed_state, s.runner_id, s.reason_code,
       s.last_agent_observation_at, s.last_transition_at
FROM endpoints.proxy_endpoints e
JOIN endpoints.endpoint_status s ON s.tenant_id=e.tenant_id AND s.endpoint_id=e.id
WHERE e.tenant_id=$1 AND (e.created_at,e.id)>($2,$3)
ORDER BY e.created_at,e.id LIMIT $4
`

type ListEndpointsParams struct {
	TenantID    uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
}

type ListEndpointsRow struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	Name                   string
	NormalizedName         string
	BindingMode            string
	AccountID              uuid.UUID
	NodeID                 uuid.UUID
	DesiredRunnerState     string
	LifecycleState         string
	DesiredGeneration      int64
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ObservedGeneration     int64
	ObservedState          string
	RunnerID               *uuid.UUID
	ReasonCode             string
	LastAgentObservationAt *time.Time
	LastTransitionAt       time.Time
}

func (q *Queries) ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]ListEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listEndpoints,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEndpointsRow
	for rows.Next() {
		var i ListEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NormalizedName,
			&i.BindingMode,
			&i.AccountID,
			&i.NodeID,
			&i.DesiredRunnerState,
			&i.LifecycleState,
			&i.DesiredGeneration,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservedGeneration,
			&i.ObservedState,
			&i.RunnerID,
			&i.ReasonCode,
			&i.LastAgentObservationAt,
			&i.LastTransitionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
