// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenancy.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTenantAdminBindings = `-- name: CountTenantAdminBindings :one
SELECT count(*)
FROM tenancy.role_bindings
WHERE tenant_id = $1
  AND role = 'tenant_admin'
`

func (q *Queries) CountTenantAdminBindings(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantAdminBindings, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantAdminBindingsForMembership = `-- name: CountTenantAdminBindingsForMembership :one
SELECT count(*)
FROM tenancy.role_bindings
WHERE tenant_id = $1
  AND membership_id = $2
  AND role = 'tenant_admin'
`

type CountTenantAdminBindingsForMembershipParams struct {
	TenantID     uuid.UUID
	MembershipID uuid.UUID
}

func (q *Queries) CountTenantAdminBindingsForMembership(ctx context.Context, arg CountTenantAdminBindingsForMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantAdminBindingsForMembership, arg.TenantID, arg.MembershipID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO tenancy.memberships (id, tenant_id, identity_id, version, created_at, updated_at)
VALUES ($1, $2, $3, 1, $4, $5)
RETURNING id, tenant_id, identity_id, version, created_at, updated_at, identity_tenant_eligible
`

type CreateMembershipParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	IdentityID uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.TenantID,
		arg.IdentityID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TenancyMembership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdentityID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityTenantEligible,
	)
	return i, err
}

const createRoleBinding = `-- name: CreateRoleBinding :one
INSERT INTO tenancy.role_bindings (id, tenant_id, membership_id, role, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, 1, $5, $6)
RETURNING id, tenant_id, membership_id, role, version, created_at, updated_at
`

type CreateRoleBindingParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	MembershipID uuid.UUID
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) (TenancyRoleBinding, error) {
	row := q.db.QueryRow(ctx, createRoleBinding,
		arg.ID,
		arg.TenantID,
		arg.MembershipID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TenancyRoleBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MembershipID,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenancy.tenants (id, slug, name, state, version, created_at, updated_at)
VALUES ($1, $2, $3, 'active', 1, $4, $5)
RETURNING id, slug, name, state, version, created_at, updated_at
`

type CreateTenantParams struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (TenancyTenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TenancyTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM tenancy.memberships WHERE id = $1
`

func (q *Queries) DeleteMembership(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRoleBinding = `-- name: DeleteRoleBinding :execrows
DELETE FROM tenancy.role_bindings WHERE id = $1
`

func (q *Queries) DeleteRoleBinding(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoleBinding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, tenant_id, identity_id, version, created_at, updated_at, identity_tenant_eligible
FROM tenancy.memberships WHERE id = $1
`

func (q *Queries) GetMembershipByID(ctx context.Context, id uuid.UUID) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i TenancyMembership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdentityID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdentityTenantEligible,
	)
	return i, err
}

const getRoleBindingByID = `-- name: GetRoleBindingByID :one
SELECT id, tenant_id, membership_id, role, version, created_at, updated_at FROM tenancy.role_bindings WHERE id = $1
`

func (q *Queries) GetRoleBindingByID(ctx context.Context, id uuid.UUID) (TenancyRoleBinding, error) {
	row := q.db.QueryRow(ctx, getRoleBindingByID, id)
	var i TenancyRoleBinding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MembershipID,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, name, state, version, created_at, updated_at FROM tenancy.tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (TenancyTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i TenancyTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTenant = `-- name: LockTenant :exec
SELECT pg_advisory_xact_lock(hashtextextended('ajiasu-tenant:' || $1::uuid::text, 0))
`

func (q *Queries) LockTenant(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockTenant, tenantID)
	return err
}

const tenantExists = `-- name: TenantExists :one
SELECT EXISTS (SELECT 1 FROM tenancy.tenants WHERE id = $1)
`

func (q *Queries) TenantExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tenantExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenancy.tenants
SET name = COALESCE($1, name), state = COALESCE($2, state),
    version = version + 1, updated_at = $3
WHERE id = $4 AND version = $5
RETURNING id, slug, name, state, version, created_at, updated_at
`

type UpdateTenantParams struct {
	Name            pgtype.Text
	State           pgtype.Text
	UpdatedAt       time.Time
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (TenancyTenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.Name,
		arg.State,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i TenancyTenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userIdentityExists = `-- name: UserIdentityExists :one
SELECT EXISTS (
    SELECT 1 FROM identity.user_identities
    WHERE id = $1 AND tenant_eligible = true
)
`

func (q *Queries) UserIdentityExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userIdentityExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
