// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gateways.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getGateway = `-- name: GetGateway :one
SELECT id, name, normalized_name, certificate_fingerprint, state, connectivity_state, gateway_version, architecture, last_heartbeat_at, session_generation, version, created_at, updated_at FROM gateways.gateways WHERE id=$1
`

func (q *Queries) GetGateway(ctx context.Context, id uuid.UUID) (GatewaysGateway, error) {
	row := q.db.QueryRow(ctx, getGateway, id)
	var i GatewaysGateway
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.CertificateFingerprint,
		&i.State,
		&i.ConnectivityState,
		&i.GatewayVersion,
		&i.Architecture,
		&i.LastHeartbeatAt,
		&i.SessionGeneration,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGateways = `-- name: ListGateways :many
SELECT id, name, normalized_name, certificate_fingerprint, state, connectivity_state, gateway_version, architecture, last_heartbeat_at, session_generation, version, created_at, updated_at FROM gateways.gateways ORDER BY created_at,id
`

func (q *Queries) ListGateways(ctx context.Context) ([]GatewaysGateway, error) {
	rows, err := q.db.Query(ctx, listGateways)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewaysGateway
	for rows.Next() {
		var i GatewaysGateway
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.CertificateFingerprint,
			&i.State,
			&i.ConnectivityState,
			&i.GatewayVersion,
			&i.Architecture,
			&i.LastHeartbeatAt,
			&i.SessionGeneration,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
