// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proxy_credentials.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getActiveProxyCredentialByPublicIdentifier = `-- name: GetActiveProxyCredentialByPublicIdentifier :one
SELECT id, tenant_id, endpoint_id, public_identifier, verifier, expires_at, revoked_at, created_at, updated_at FROM endpoints.proxy_credentials WHERE tenant_id=$1 AND public_identifier=$2 AND revoked_at IS NULL
`

type GetActiveProxyCredentialByPublicIdentifierParams struct {
	TenantID         uuid.UUID
	PublicIdentifier string
}

func (q *Queries) GetActiveProxyCredentialByPublicIdentifier(ctx context.Context, arg GetActiveProxyCredentialByPublicIdentifierParams) (EndpointsProxyCredential, error) {
	row := q.db.QueryRow(ctx, getActiveProxyCredentialByPublicIdentifier, arg.TenantID, arg.PublicIdentifier)
	var i EndpointsProxyCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.PublicIdentifier,
		&i.Verifier,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProxyCredential = `-- name: GetProxyCredential :one
SELECT id, tenant_id, endpoint_id, public_identifier, verifier, expires_at, revoked_at, created_at, updated_at FROM endpoints.proxy_credentials WHERE tenant_id=$1 AND id=$2
`

type GetProxyCredentialParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetProxyCredential(ctx context.Context, arg GetProxyCredentialParams) (EndpointsProxyCredential, error) {
	row := q.db.QueryRow(ctx, getProxyCredential, arg.TenantID, arg.ID)
	var i EndpointsProxyCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.PublicIdentifier,
		&i.Verifier,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxyCredentials = `-- name: ListProxyCredentials :many
SELECT id, tenant_id, endpoint_id, public_identifier, verifier, expires_at, revoked_at, created_at, updated_at FROM endpoints.proxy_credentials WHERE tenant_id=$1 AND endpoint_id=$2 ORDER BY created_at,id
`

type ListProxyCredentialsParams struct {
	TenantID   uuid.UUID
	EndpointID uuid.UUID
}

func (q *Queries) ListProxyCredentials(ctx context.Context, arg ListProxyCredentialsParams) ([]EndpointsProxyCredential, error) {
	rows, err := q.db.Query(ctx, listProxyCredentials, arg.TenantID, arg.EndpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EndpointsProxyCredential
	for rows.Next() {
		var i EndpointsProxyCredential
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.PublicIdentifier,
			&i.Verifier,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
