// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*) FROM accounts.accounts WHERE tenant_id = $1
`

func (q *Queries) CountAccounts(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveReservations = `-- name: CountActiveReservations :one
SELECT count(*) FROM accounts.account_capacity_reservations
WHERE tenant_id = $1 AND account_id = $2 AND expires_at > $3
`

type CountActiveReservationsParams struct {
	TenantID  uuid.UUID
	AccountID uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CountActiveReservations(ctx context.Context, arg CountActiveReservationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReservations, arg.TenantID, arg.AccountID, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, name, normalized_name, state, health, membership_id, membership_expires_at, labels, max_concurrency, health_successes, health_failures, last_health_at, version, created_at, updated_at FROM accounts.accounts WHERE tenant_id = $1 AND id = $2
`

type GetAccountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (AccountsAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.TenantID, arg.ID)
	var i AccountsAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NormalizedName,
		&i.State,
		&i.Health,
		&i.MembershipID,
		&i.MembershipExpiresAt,
		&i.Labels,
		&i.MaxConcurrency,
		&i.HealthSuccesses,
		&i.HealthFailures,
		&i.LastHealthAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCredential = `-- name: GetActiveCredential :one
SELECT tenant_id, account_id, version, provider, key_id, ciphertext, wrapped_dek, external_ref, created_by, created_at, retired_at FROM accounts.account_credentials
WHERE tenant_id = $1 AND account_id = $2 AND retired_at IS NULL
`

type GetActiveCredentialParams struct {
	TenantID  uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) GetActiveCredential(ctx context.Context, arg GetActiveCredentialParams) (AccountsAccountCredential, error) {
	row := q.db.QueryRow(ctx, getActiveCredential, arg.TenantID, arg.AccountID)
	var i AccountsAccountCredential
	err := row.Scan(
		&i.TenantID,
		&i.AccountID,
		&i.Version,
		&i.Provider,
		&i.KeyID,
		&i.Ciphertext,
		&i.WrappedDek,
		&i.ExternalRef,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, tenant_id, name, normalized_name, state, health, membership_id, membership_expires_at, labels, max_concurrency, health_successes, health_failures, last_health_at, version, created_at, updated_at FROM accounts.accounts
WHERE tenant_id = $1 AND (created_at, id) > ($2, $3)
ORDER BY created_at, id LIMIT $4
`

type ListAccountsParams struct {
	TenantID    uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]AccountsAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountsAccount
	for rows.Next() {
		var i AccountsAccount
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NormalizedName,
			&i.State,
			&i.Health,
			&i.MembershipID,
			&i.MembershipExpiresAt,
			&i.Labels,
			&i.MaxConcurrency,
			&i.HealthSuccesses,
			&i.HealthFailures,
			&i.LastHealthAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
