// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountsAccount struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	Name                string
	NormalizedName      string
	State               string
	Health              string
	MembershipID        pgtype.Text
	MembershipExpiresAt *time.Time
	Labels              []byte
	MaxConcurrency      int32
	HealthSuccesses     int32
	HealthFailures      int32
	LastHealthAt        *time.Time
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type AccountsAccountCapacityReservation struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	AccountID uuid.UUID
	OwnerID   uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type AccountsAccountCredential struct {
	TenantID    uuid.UUID
	AccountID   uuid.UUID
	Version     int64
	Provider    string
	KeyID       string
	Ciphertext  []byte
	WrappedDek  []byte
	ExternalRef string
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
	RetiredAt   *time.Time
}

type PoolsAccountPool struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	NormalizedName string
	Strategy       string
	Selector       []byte
	State          string
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PoolsAccountPoolMembership struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	PoolID    uuid.UUID
	AccountID uuid.UUID
	Priority  int32
	Weight    int32
	Enabled   bool
	ExpiresAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenancyMembership struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	IdentityID uuid.UUID
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type TenancyRoleBinding struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	MembershipID uuid.UUID
	Role         string
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TenancyTenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	State     string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TenancyTenantQuota struct {
	TenantID           uuid.UUID
	MaxAccounts        int32
	MaxPools           int32
	MaxPoolMemberships int32
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
