// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pools.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPools = `-- name: CountPools :one
SELECT count(*) FROM pools.account_pools WHERE tenant_id = $1
`

func (q *Queries) CountPools(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPools, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccountPool = `-- name: GetAccountPool :one
SELECT id, tenant_id, name, normalized_name, strategy, selector, state, version, created_at, updated_at FROM pools.account_pools WHERE tenant_id = $1 AND id = $2
`

type GetAccountPoolParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetAccountPool(ctx context.Context, arg GetAccountPoolParams) (PoolsAccountPool, error) {
	row := q.db.QueryRow(ctx, getAccountPool, arg.TenantID, arg.ID)
	var i PoolsAccountPool
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NormalizedName,
		&i.Strategy,
		&i.Selector,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountPools = `-- name: ListAccountPools :many
SELECT id, tenant_id, name, normalized_name, strategy, selector, state, version, created_at, updated_at FROM pools.account_pools
WHERE tenant_id = $1 AND (created_at, id) > ($2, $3)
ORDER BY created_at, id LIMIT $4
`

type ListAccountPoolsParams struct {
	TenantID    uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
}

func (q *Queries) ListAccountPools(ctx context.Context, arg ListAccountPoolsParams) ([]PoolsAccountPool, error) {
	rows, err := q.db.Query(ctx, listAccountPools,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolsAccountPool
	for rows.Next() {
		var i PoolsAccountPool
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NormalizedName,
			&i.Strategy,
			&i.Selector,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoolMemberships = `-- name: ListPoolMemberships :many
SELECT id, tenant_id, pool_id, account_id, priority, weight, enabled, expires_at, created_at, updated_at FROM pools.account_pool_memberships
WHERE tenant_id = $1 AND pool_id = $2 AND (created_at, id) > ($3, $4)
ORDER BY created_at, id LIMIT $5
`

type ListPoolMembershipsParams struct {
	TenantID    uuid.UUID
	PoolID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
	Limit       int32
}

func (q *Queries) ListPoolMemberships(ctx context.Context, arg ListPoolMembershipsParams) ([]PoolsAccountPoolMembership, error) {
	rows, err := q.db.Query(ctx, listPoolMemberships,
		arg.TenantID,
		arg.PoolID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolsAccountPoolMembership
	for rows.Next() {
		var i PoolsAccountPoolMembership
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PoolID,
			&i.AccountID,
			&i.Priority,
			&i.Weight,
			&i.Enabled,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
