// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotas.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getTenantQuota = `-- name: GetTenantQuota :one
SELECT tenant_id, max_accounts, max_pools, max_pool_memberships, version, created_at, updated_at FROM tenancy.tenant_quotas WHERE tenant_id = $1
`

func (q *Queries) GetTenantQuota(ctx context.Context, tenantID uuid.UUID) (TenancyTenantQuota, error) {
	row := q.db.QueryRow(ctx, getTenantQuota, tenantID)
	var i TenancyTenantQuota
	err := row.Scan(
		&i.TenantID,
		&i.MaxAccounts,
		&i.MaxPools,
		&i.MaxPoolMemberships,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTenantQuota = `-- name: LockTenantQuota :one
SELECT tenant_id, max_accounts, max_pools, max_pool_memberships, version, created_at, updated_at FROM tenancy.tenant_quotas WHERE tenant_id = $1 FOR UPDATE
`

func (q *Queries) LockTenantQuota(ctx context.Context, tenantID uuid.UUID) (TenancyTenantQuota, error) {
	row := q.db.QueryRow(ctx, lockTenantQuota, tenantID)
	var i TenancyTenantQuota
	err := row.Scan(
		&i.TenantID,
		&i.MaxAccounts,
		&i.MaxPools,
		&i.MaxPoolMemberships,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
